# Generated by Django 6.0.3 on 2026-03-05 10:22

from django.db import migrations, models


def seed_dynamic_content(apps, schema_editor):
    SiteSettings = apps.get_model("website", "SiteSettings")
    ServiceOffering = apps.get_model("website", "ServiceOffering")
    ClinicLocation = apps.get_model("website", "ClinicLocation")
    PatientResource = apps.get_model("website", "PatientResource")
    HomeMetric = apps.get_model("website", "HomeMetric")

    if not SiteSettings.objects.exists():
        SiteSettings.objects.create()

    if not ServiceOffering.objects.exists():
        ServiceOffering.objects.bulk_create(
            [
                ServiceOffering(
                    title="Preventive Screening",
                    description="Full body screening, early risk detection, and practical wellness recommendations.",
                    cta_name="book_screening",
                    display_order=1,
                ),
                ServiceOffering(
                    title="Natural Supplement Guidance",
                    description="Personalized supplement support based on your wellness goals and health profile.",
                    cta_name="products",
                    display_order=2,
                ),
                ServiceOffering(
                    title="Lifestyle and Chronic Condition Support",
                    description="Structured plans for stress, sleep, nutrition, and long-term condition management.",
                    cta_name="book_screening",
                    display_order=3,
                ),
                ServiceOffering(
                    title="Health Education",
                    description="Evidence-informed education to help you make better daily health decisions.",
                    cta_name="blog",
                    display_order=4,
                ),
            ]
        )

    if not ClinicLocation.objects.exists():
        ClinicLocation.objects.bulk_create(
            [
                ClinicLocation(
                    name="Kuol Health Solutions - Nairobi",
                    address="JKUAT Towers, Kenyatta Avenue, Nairobi",
                    phone="+254 795 225 892",
                    whatsapp="+254 784 768 933",
                    hours="Mon-Sat: 8:00am - 6:00pm",
                    maps_url="https://maps.google.com/?q=JKUAT+Towers+Kenyatta+Avenue+Nairobi",
                    services_text="Full body screening\nConsultation\nSupplement guidance\nOrder support",
                    display_order=1,
                ),
                ClinicLocation(
                    name="Virtual Care Desk (Kenya-wide)",
                    address="Remote support via phone and WhatsApp",
                    phone="+254 795 225 892",
                    whatsapp="+254 784 768 933",
                    hours="Mon-Sat: 8:00am - 7:00pm",
                    maps_url="https://wa.me/254784768933",
                    services_text="Follow-up support\nProduct guidance\nOrder coordination\nAppointment booking",
                    display_order=2,
                ),
            ]
        )

    if not PatientResource.objects.exists():
        PatientResource.objects.bulk_create(
            [
                PatientResource(
                    title="Book Appointment",
                    description="Reserve a screening and consultation slot that works for you.",
                    url_name="book_screening",
                    label="Book Screening",
                    display_order=1,
                ),
                PatientResource(
                    title="Order and Billing Support",
                    description="Submit supplement orders and receive payment and fulfillment guidance.",
                    url_name="order_request",
                    label="Start Order",
                    display_order=2,
                ),
                PatientResource(
                    title="Health Education",
                    description="Learn practical wellness strategies from our latest health articles.",
                    url_name="blog",
                    label="Read Articles",
                    display_order=3,
                ),
                PatientResource(
                    title="Contact and Follow-Up",
                    description="Reach our care team quickly for updates, guidance, and next steps.",
                    url_name="contact",
                    label="Contact Team",
                    display_order=4,
                ),
            ]
        )

    if not HomeMetric.objects.exists():
        HomeMetric.objects.bulk_create(
            [
                HomeMetric(value="3+ Years", title="Wellness partner in Kenya", display_order=1),
                HomeMetric(value="24h", title="Typical follow-up window", display_order=2),
                HomeMetric(value="96%", title="Client satisfaction target", display_order=3),
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("address", models.CharField(max_length=220)),
                ("phone", models.CharField(max_length=30)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("hours", models.CharField(max_length=120)),
                ("maps_url", models.URLField(blank=True)),
                (
                    "services_text",
                    models.TextField(
                        blank=True,
                        help_text="Enter one service per line for display badges.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured_home", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HomeMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=220)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PatientResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField()),
                (
                    "url_name",
                    models.CharField(
                        choices=[
                            ("book_screening", "Book Screening"),
                            ("order_request", "Order Support"),
                            ("blog", "Health Education"),
                            ("contact", "Contact"),
                            ("products", "Supplements"),
                            ("services", "Services"),
                            ("locations", "Locations"),
                        ],
                        default="book_screening",
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(default="Open", max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                (
                    "cta_name",
                    models.CharField(
                        choices=[
                            ("book_screening", "Book Screening"),
                            ("products", "Supplements"),
                            ("order_request", "Order Support"),
                            ("blog", "Health Education"),
                            ("contact", "Contact"),
                        ],
                        default="book_screening",
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured_home", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Kuol Health Solutions", max_length=120),
                ),
                (
                    "meta_description",
                    models.CharField(
                        default="Preventive care, wellness screening, and natural supplement guidance in Nairobi.",
                        max_length=255,
                    ),
                ),
                (
                    "utility_location_label",
                    models.CharField(default="Nairobi Main Clinic", max_length=120),
                ),
                (
                    "utility_hours",
                    models.CharField(default="Mon-Sat 8:00am - 6:00pm", max_length=120),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+254 795 225 892", max_length=30),
                ),
                (
                    "contact_whatsapp",
                    models.CharField(default="+254 784 768 933", max_length=30),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="KuolHealthsolutions@gmail.com", max_length=254
                    ),
                ),
                (
                    "facility_address",
                    models.CharField(
                        default="JKUAT Towers, Kenyatta Avenue, Nairobi", max_length=180
                    ),
                ),
                (
                    "footer_summary",
                    models.TextField(
                        default="Preventive healthcare support through screening, education, and natural supplement guidance. We help individuals take practical steps toward healthier living."
                    ),
                ),
                (
                    "home_hero_badge",
                    models.CharField(
                        default="Trusted Preventive Care in Kenya", max_length=120
                    ),
                ),
                (
                    "home_hero_title",
                    models.CharField(
                        default="Better health starts with early screening and guided daily choices.",
                        max_length=220,
                    ),
                ),
                (
                    "home_hero_description",
                    models.TextField(
                        default="Kuol Health Solutions combines preventive screening, practical consultation, and natural supplement guidance to support individuals managing chronic and lifestyle conditions."
                    ),
                ),
                (
                    "about_heading",
                    models.CharField(
                        default="About Kuol Health Solutions", max_length=150
                    ),
                ),
                (
                    "about_intro",
                    models.TextField(
                        default="A preventive health and wellness organization supporting chronic and lifestyle condition management."
                    ),
                ),
                (
                    "about_body",
                    models.TextField(
                        default="We provide natural supplements designed to support the body, strengthen immunity, and promote long-term wellness through early intervention and practical guidance."
                    ),
                ),
                (
                    "mission_statement",
                    models.TextField(
                        default="To promote preventive healthcare and support chronic and lifestyle condition management through certified natural supplements, screening, and continuous health education."
                    ),
                ),
                (
                    "vision_statement",
                    models.TextField(
                        default="To become a trusted leader in preventive health and wellness, empowering communities to live healthier and more productive lives through natural and science-supported solutions."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.RunPython(seed_dynamic_content, migrations.RunPython.noop),
    ]
