# Generated by Django 6.0.3 on 2026-03-24 17:14

import django.core.validators
import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_cliniclocation_homemetric_patientresource_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=website.models.media_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "gif",
                                    "mp4",
                                    "webm",
                                    "mov",
                                    "m4v",
                                    "ogg",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Use this as the main image/video for cards and previews.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_media",
                        to="website.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "About media",
                "verbose_name_plural": "About media",
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=website.models.media_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "gif",
                                    "mp4",
                                    "webm",
                                    "mov",
                                    "m4v",
                                    "ogg",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Use this as the main image/video for cards and previews.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="website.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=website.models.media_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "gif",
                                    "mp4",
                                    "webm",
                                    "mov",
                                    "m4v",
                                    "ogg",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Use this as the main image/video for cards and previews.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="website.serviceoffering",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestimonialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=website.models.media_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "gif",
                                    "mp4",
                                    "webm",
                                    "mov",
                                    "m4v",
                                    "ogg",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Use this as the main image/video for cards and previews.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "testimonial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="website.testimonial",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
    ]
