# Generated by Django 6.0.3 on 2026-03-24 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_aboutmedia_productmedia_servicemedia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_background_image",
            field=models.FileField(
                blank=True,
                help_text="Optional hero background image shown on the home page.",
                upload_to="site",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                    )
                ],
            ),
        ),
    ]
