# Generated by Django 6.0.3 on 2026-03-24 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_sitesettings_hero_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="featured_image",
            field=models.FileField(
                blank=True,
                upload_to="blog",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="cliniclocation",
            name="featured_image",
            field=models.FileField(
                blank=True,
                upload_to="locations",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="homemetric",
            name="featured_image",
            field=models.FileField(
                blank=True,
                upload_to="metrics",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                    )
                ],
            ),
        ),
    ]
